version: '3.1'
services:
  ruby:
    build: docker/
    image: debiki/ed-jekyll-comments-demo
    volumes:
      - ./volume/:/opt/volume/
    ports:
      - '4001:4000'
      - '4002:4002'
    command: sleep 999999

#  sudo docker-compose exec ruby bash
#  cd /opt/volume/test-site
#  bundle exec jekyll serve --host 0.0.0.0 --port 4002


# vim: et ts=2 sw=2
